weaveworks/footloose

.gitignore
footloose.go

footloose.go: Rename default cfg to footloose.yaml

---

ssh.go

Prevent panic! 😱 
cc @dlespiau

ssh.go: Add argument validation

---

.travis.yml
config.go
go.mod
go.sum
tests/.gitignore
tests/e2e_test.go
tests/test-create-delete.cmd
tests/test-create-delete.golden.output

Embryo of CI tests

---

defaults.go
footloose.go
images/centos7/Dockerfile
pkg/cluster/cluster.go
pkg/cluster/machine.go
pkg/config/machine.go
tests/test-docker-in-docker.yaml

The various commit messages have some details. This is basically an attempt at making the thing work on macOS.

Port Mapping support and SSH login through a host port

---

README.md
config.go
config_create.go
tests/test-create-delete.cmd
tests/test-ssh-remote-command.cmd

config: Add a create sub-command

---

.travis.yml
images/centos7/Dockerfile

centos7: Use SIGRTMIN+3 as the stop signal

---

defaults.go

config: Default to the 0.1.0 image

---

images/amazonlinux2/Dockerfile

I only did basic testing with the footloose.yaml file you suggested and it appears to work as intended (create and ssh worked).
Fix for #59

Added amazonlinux2 dockerfile

---

README.md
examples/fedora29-htop/Dockerfile

This can give people some ideas and is useful to speed up CI runs!
Fixes: #26

examples: Provide a simple example of custom image

---

examples/ansible/README.md
examples/ansible/ansible.cfg
examples/ansible/example1.yml
examples/ansible/inventory.txt

providing a basic ansible integration example. Needs ansible 2.0+ installed
fix #76

ansible integration example

---

pkg/cluster/cluster.go
tests/README.md
tests/test-create-delete-idempotent-%image.cmd
tests/test-create-delete-idempotent-%image.output

Made create and delete idempotent.

---

pkg/cluster/cluster.go
pkg/cluster/machine.go

Sorry, it should have started out like this. :)
It's much cleaner.

Refactored run check to be part of the machine.

---

config_create.go
pkg/cluster/cluster.go
tests/test-create-config-already-exists-%image.cmd
tests/test-create-config-already-exists-fedora29.cmd

Added check to not to overwrite a configuration file if it is already present.

---

README.md

Add very simple FAQ and help sections.

add FAQ and Help sections

---

.goreleaser.yml

release: Add a brew target using the weaveworks homebrew tap

---

.travis.yml

Build and publish docker images in CI

---

examples/simple-hostPort/README.md
examples/simple-hostPort/footloose_config_example.yaml

I didn't manage to get the 'config create' command flag for hostPort mapping, is it documented ? 
Fix #105

Example host port

---

pkg/cluster/cluster.go
pkg/cluster/formatter.go
tests/test-show-ubuntu18.04.golden.output

Parity between show one and show more in case json parser is used.

---

pkg/cluster/formatter.go
tests/test-show-ubuntu18.04.golden.output

update #115 
- [o ] Headers should be left aligned 
- [x ] no space between the first value

Display left aligned #115

---

pkg/cluster/cluster.go
pkg/cluster/formatter.go
pkg/cluster/machine.go
show.go
tests/test-show-ubuntu18.04.golden.output

Sorting the list of machines.

---

pkg/cluster/cluster.go

@dlespiau grumble grumble. :D
Fixes: #127

Fixing the spec being reused for all machines

---

README.md
images/clearlinux/Dockerfile
tests/variables.json

Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>

Add clearlinux docker image

---

pkg/cluster/cluster.go
start.go
stop.go
tests/test-start-stop-specific-%image.cmd
tests/test-start-stop-specific-%image.golden.output

This enables to start and stop specific machines
Fixes #108

Cluster Start Stop

---

pkg/cluster/cluster.go

This changes machine selection from container name to hostname
Fixes #109

show: change machine selection

---

config_create.go
pkg/cluster/cluster.go
pkg/config/cluster.go
pkg/config/machine.go
tests/test-create-invalid-fedora29.cmd
tests/test-create-invalid-fedora29.static

Adding config file validation with machine name checking
#125

Config file

---

pkg/cluster/cluster.go
pkg/cluster/formatter.go
tests/test-show-ubuntu18.04.golden.output

- Remove the first empty column in `show`
- Remove "with name" from logging messages

A couple of tweaks

---

tests/test-create-delete-%image.cmd
tests/test-create-delete-persistent-%image.cmd
tests/test-create-stop-start-%image.cmd

This uses more selective docker ps command in tests
Fixes #145

Tests ps commands

---

tests/test-config-get-ubuntu18.04.cmd
tests/test-create-delete-%image.cmd
tests/test-create-delete-idempotent-%image.cmd
tests/test-create-delete-persistent-%image.cmd
tests/test-create-stop-start-%image.cmd
tests/test-show-ubuntu18.04.cmd
tests/test-ssh-remote-command-%image.cmd
tests/test-ssh-user-%image.cmd
tests/test-start-stop-specific-%image.cmd

@dlespiau I believe I have fixed the failing tests. The attached file shows output from running all tests. Please let me know how it looks and if I missed anything.
[tests.txt](https://github.com/weaveworks/footloose/files/3184377/tests.txt)

Add --override to failing tests

---

.travis.yml
README.md
defaults.go
pkg/cluster/cluster.go
pkg/cluster/formatter.go
pkg/cluster/machine.go
pkg/config/machine.go
pkg/docker/pull.go
pkg/exec/local.go
pkg/ignite/create.go
pkg/ignite/doc.go
pkg/ignite/ignite.go
pkg/ignite/rm.go
pkg/ignite/stop.go
tests/test-config-get-ubuntu18.04.golden.output
tests/test-show-ubuntu18.04.golden.output

This PR is based on #177 by @luxas 
Adds delete functionality and refactors ignite functionality to its own package.

Ignite support #177 - Continuation

---

pkg/config/machine.go
pkg/ignite/create.go

Adds Support to Copy Files (thru Ignite) into the VM.

Adds Support to Copy Files (thru Ignite) into the VM

---

show.go

Fixing #162

---

pkg/cluster/cluster.go

Just replaced long code under the `if` statement with `continue`

remove big if

---

config_create.go
tests/test-config-get-ubuntu18.04.cmd
tests/test-config-get-ubuntu18.04.golden.output

This adds possibility to set networks names when creating the config file
Fixes #161

add network flag when creating config file

---

pkg/ignite/create.go

Ignite CopyFiles: Converts to Absolute path if needed.

Ignite CopyFiles: Converts to Absolute path if needed

---

pkg/ignite/create.go

cc @twelho @dlespiau 
This is needed for v0.6.0

Fix a small bug in the portmapping assignment

---

pkg/cluster/cluster.go
pkg/cluster/machine.go
pkg/exec/exec.go
pkg/ignite/create.go
pkg/ignite/doc.go
pkg/ignite/ignite.go
pkg/ignite/inspect.go
pkg/ignite/rm.go
pkg/ignite/stop.go

Fixes Issue #189

---

pkg/cluster/cluster.go
pkg/ignite/start.go

Fixes issue #191.
Depends on issue #189

Fixes issue #191

---

.travis.yml
config_get.go
pkg/cluster/cluster.go
pkg/cluster/cluster_test.go
pkg/cluster/machine.go
pkg/config/cluster.go
pkg/config/get.go
pkg/config/machine.go
pkg/ignite/create.go

Fixes #200 
I added golangci-lint in travis-ci and also fixed all current issues which suggested by linter.

Add golangci-lint in travis-ci #200

---

pkg/cluster/cluster.go
pkg/cluster/machine.go
tests/test-show-ubuntu18.04.golden.output

This changes the way the JSON formatter gets the host ports

json formatter ports

---

version.go

version: Don't panic when failing to retrieve version from github

---

go.mod
pkg/cluster/cluster.go
pkg/cluster/formatter.go
pkg/cluster/machine.go
pkg/cluster/runtime_network.go
pkg/docker/inspect.go

Add networking information to the machine status

---

pkg/docker/pull.go

Fix https://github.com/weaveworks/footloose/issues/222

docker: Display stderr when docker daemon isn't running

---

pkg/api/machine.go
pkg/cluster/formatter.go
pkg/cluster/machine.go
pkg/cluster/runtime_network.go
show.go
tests/test-show-ubuntu18.04.golden.output

Refactoring Formatter to use MachineStatus everywhere.

---

.goreleaser.yml
.travis.yml

Fix: goreleaser config

---

README.md
images/ubuntu20.04/Dockerfile
tests/variables.json

This PR is to add ubuntu 20.04 image.
Dockerfile is copied from 18.04.
Closes #248
Signed-off-by: Tam Mach <sayboras@yahoo.com>

feat(image): Add ubuntu 20.04 image
