README.md, config.go, pkg/cluster/cluster.go, pkg/config/machine.go, tests/e2e_test.go, tests/test-docker-in-docker.cmd, tests/test-docker-in-docker.golden.output, tests/test-docker-in-docker.yaml
This PR introduces Volume support for container machines, which allows running docker in docker (/var/lib/docker cannot be itself already an overlay).
Fixes: #4
=> Docker in docker support

pkg/config/machine.go
Two issues there:
- The comment was referring to the old field name
- N machines, the index is between 0 and N-1 :)
=> config: Fix the HostPort doc string

.gitignore, go.mod, pkg/cluster/machine.go
Ran into the following error, this fixes it:
```
FATA[0000] hostport: failed to parse string to int: strconv.Atoi: parsing "'32768'": invalid syntax
```
No idea why the `go.mod` file was now updated, but I commited that?
cc @dlespiau
=>  pkg/cluster/machine.go: Remove quotes from port

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go
Fixes #40.
Manual, end-to-end test in addition to the unit test included in the PR:
```console
$ footloose create
INFO[0000] Image: quay.io/footloose/centos7 present locally 
INFO[0000] Creating machine: cluster-node0 ...          
INFO[0001] Creating machine: cluster-node1 ...          
$ docker ps
CONTAINER ID        IMAGE                       COMMAND             CREATED             STATUS              PORTS                  NAMES
b3f100b6b6c1        quay.io/footloose/centos7   "/sbin/init"        2 seconds ago       Up 1 second         0.0.0.0:2223->22/tcp   cluster-node1
95b4054646d9        quay.io/footloose/centos7   "/sbin/init"        3 seconds ago       Up 2 seconds        0.0.0.0:2222->22/tcp   cluster-node0
```
=> Swap hostPort and containerPort

README.md, images/debian10/Dockerfile, tests/README.md, tests/variables.json
Debian 10 "Buster" had a *full freeze* this week (on 2019-03-12) and will be released somewhere later this year (mid 2019).
I thought a base image might come in handy, so here it is.
To be honest it's mostly a copy of `footloose/images/ubuntu18.04`.
Testing done:
```txt
$ ./make-image.sh build debian10
$ footloose config create --image quay.io/footloose/debian10
$ footloose create
INFO[0000] Image: quay.io/footloose/debian10 present locally
INFO[0000] Creating machine: cluster-node0 ...
$ footloose ssh root@node0
Linux node0 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.
Debian GNU/Linux …
```
=> Adding base image for Debian Buster

tests/test-docker-in-docker-debian10.cmd, tests/test-docker-in-docker-debian10.golden.output, tests/test-docker-in-docker-debian10.yaml
This will fix #92.
Testing done.
```txt
go test -v -run TestEndToEnd/test-docker-in-docker-debian10
=== RUN   TestEndToEnd
=== RUN   TestEndToEnd/test-docker-in-docker-debian10
INFO[0000] Creating SSH key: test-docker-in-docker-debian10-key ...
INFO[0002] Image: quay.io/footloose/debian10 present locally
INFO[0002] Creating machine: test-docker-in-docker-debian10-node0 ...
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
--- 8< --- cut ---
Status: Downloaded newer image for busybox:latest
INFO[0000] Deleting machine: test-docker-in-docker-debian10-node0 ...
--- PASS: TestEndToEnd (54.73s)
--- PASS: TestEndToEnd/test-docker-in-docker-debian10 (54.73s)
PASS
ok  	github.com/weaveworks/footloose/tests	54.752s
```
=> Add a test running docker in docker with debian10

pkg/cluster/cluster.go
In some cases, when there are many identities configured client side, the
server may give up on trying all of them and fails with:
Too many authentication failures
Instruct ssh to only the specified identity.
=> ssh: Specify IdentitiesOnly=yes

version.go
goreleaser should set the version through an ldflag, see:
https://goreleaser.com/customization/
default is `-s -w -X main.version={{.Version}} ....`
Fixes: #57
=> version: Add a version command

.travis.yml, defaults.go
The default image was hardcoded to "0.1.0", with this PR we now use the latest released tag (or "latest" when compiling from git).
Fixes: #99
=> Ensure we use a fixed Docker tag in the default configuration

go.mod, go.sum, pkg/cluster/cluster.go, pkg/config/cluster.go
This PR enables environment variable expansion for the private key file.
With it one can use an already existing key by passing to the config file:
```yaml
cluster:
name: cluster
privateKey: $HOME/.ssh/id_rsa
machines:
- count: 1
...
```
=> Expand environment variables for private key file

README.md
=> Add line about how to use Ubuntu images

pkg/cluster/formatter.go, tests/test-show-ubuntu18.04.golden.output
this changes format in output and table by renaming attribute name to container.
Fixes #112
=> formatter: Rename "name" field to "container" and remove "/"

pkg/cluster/cluster.go, pkg/cluster/formatter.go, pkg/cluster/machine.go
Containers follow the OCI lifecycle: create, start, stop, delete.
Currently the IsRunning function tests if the container name exist. This isn't
a condition that tells us if the container is started, only that it's been
created.
- Let's rename IsRunning to IsCreated to reflect that reality.
- Make the formatters use IsStart to decide whether the machine is running or
not.
Fixes: #114
=> cluster: Fix the Stopped/Running logic

images/clearlinux/Dockerfile, images/debian10/Dockerfile, images/ubuntu16.04/Dockerfile, images/ubuntu18.04/Dockerfile, tests/test-basic-commands-%image.cmd
This installs the package `sudo` in Ubuntu images by default. Other images already do that; this PR makes ubuntu follow suit.
Fixes: #143
=> Add sudo to all Docker images

show.go
Nothing fancy, just `fotoloose status` alias for `footloose show` command.
=> Add status alias to show command

README.md, config_create.go, config_get.go, create.go, delete.go, footloose.go, show.go, ssh.go, start.go, stop.go
It can be handy to specify the config file through an env variable so we don't have to always specify the `--config` option.
=> FOOTLOOSE_CONFIG env variable

pkg/cluster/cluster.go
By default a `tmpfs` mount in Docker will be done with a `noexec` flag, which will prevent files placed on the filesystem from being directly executable.
This is contrary to the way `/tmp` is mounted usually (from a production ubuntu ec2 instance: `tmpfs on /tmp type tmpfs (rw,nosuid,nodev)`, where `noexec` isn't in place.
It avoids placing temporary scripts on /tmp and executing them, which a number of installers are making use off.
My proposed change ensures, that files placed on `/tmp` with executable flag can be run from there, just like they can on a traditional server.
I'd perhaps even like mounts to be somewhat configurable down the road to ensure higher compatibility with different distributions. For now, this shall get my current issue out the way though 👌
Thank you for …
=> ensures files in /tmp with executable mode are executable

examples/user-defined-network/README.md, examples/user-defined-network/footloose_config_example_network.yaml, pkg/cluster/cluster.go, pkg/config/machine.go
This implements https://github.com/weaveworks/footloose/issues/158
The config file has to be edited manually, also the docker network has first to be created by the user before starting the cluster, otherwise you'll receive a docker daemon error.
=> added support for used-defined networks and example how to use it.

images/ubuntu16.04/Dockerfile, images/ubuntu18.04/Dockerfile
Resolves #154 
If /etc/machine-id is empty at container start, we get distinct machine ids across containers.
=> Clear out /etc/machine-id and /var/lib/dbus/machine-id after installing systemd

tests/variables.json
I'd like to release 0.5.0 but those tests aren't passing anymore (eeeeek!).
Instead of blocking the release on that, let's disable them for now™.
=> tests: Disable ubuntu 16.04 tests

pkg/cluster/machine.go, pkg/ignite/create.go
Updates Footloose's interface to `ignite`, adds a root check and implements more robust port map handling for Ignite VMs started via Footloose.
=> Update and fix Ignite backend support in Footloose

pkg/cluster/cluster.go, pkg/cluster/machine.go, pkg/config/machine.go, pkg/ignite/create.go, pkg/ignite/inspect.go, pkg/ignite/rm.go, pkg/ignite/start.go, pkg/ignite/stop.go
Fixes the creation check and nits of https://github.com/weaveworks/footloose/pull/190, also adds comments, improves code readability, and removes some duplicate code when fetching VM details.
cc @luxas
=> Clean up the Ignite code, perform creation check before deleting a VM

pkg/config/machine.go, pkg/ignite/create.go
Probably just a typo, the tag is `diskSize` instead of `disk` to be consistent with Ignite spec.
cc @luxas
=> Ignite backend: Fix VM disk size JSON tag to be "diskSize" following Ignite spec

go.mod, go.sum, pkg/cluster/machine.go, pkg/ignite/ignite.go
Make Footloose require [v0.5.2](https://github.com/weaveworks/ignite/releases/tag/v0.5.2) of Ignite when using the Ignite backend.
=> Add a version check for Ignite, require v0.5.2

.gitignore, Makefile
The Makefile uses vendored dependencies to speed up the Docker build (no need to re-download on every build). Footloose doesn't include vendored dependencies in the source tree, so I added a gitignore entry for the `vendor` directory. That can be kept or removed based on people's opinions on keeping the `vendor` directory in-tree.
=> Add a Makefile, enable building Footloose in a Docker container

pkg/cluster/cluster.go, pkg/cluster/cluster_test.go, pkg/cluster/formatter.go, pkg/cluster/machine.go, pkg/cluster/runtime_network.go, pkg/cluster/runtime_network_test.go
This adds runtime network information to `show` command.
I inform that one test has been changed because it was failing. I did not just change it to pass, for me it makes sense to change it, but please take a look.
Fixes #163
=> add network info to show command

README.md
Changes the Ignite example configuration in the README to use the recently renamed `diskSize`.
cc @luxas
=> Ignite: update the README example to use diskSize instead of disk

RELEASING.md
closes https://github.com/weaveworks/footloose/issues/205
(had time to work on this today while waiting for other things to spin up in the background)
I committed each item separately so you could take each on its own (or not).  I bet, now that we're looking at it, for the two related to the user-defined-network example it'd be fine if we just changed it to `:latest` and removed it from the list.  If you'd like me to do that and remove those two from the list I can happily and quickly do so.
=> Adds RELEASING.md

.travis.yml, defaults.go, go.mod, go.sum, pkg/api/api.go, pkg/api/cluster.go, pkg/api/db.go, pkg/api/key.go, pkg/api/machine.go, pkg/api/response.go, pkg/client/client.go, pkg/client/client_test.go, pkg/cluster/cluster.go, pkg/cluster/formatter.go, pkg/cluster/key_store.go, pkg/cluster/machine.go, pkg/config/cluster.go, pkg/config/key.go, pkg/config/machine.go, serve.go, serve_test.go, show.go
At the moment, footloose is geared towards the command line. Turns out we'd like programs to create and delete clusters too.
This PR introduces `footloose serve` that will start such a server, defining a REST API that can be used by anyone. A go client is available in `pkg/client`.
**TODO**:
=> Long running footloose server and control API

version.go
Fix https://github.com/weaveworks/footloose/issues/209
=> version: Don't show version when build binary without ldflags

examples/user-defined-network/README.md, examples/user-defined-network/footloose.yaml
The user-defined-network example doesn't work out of the box, from the looks of things this is because networks is an array.  I think this works, though!
=> Fix documentation in examples/user-defined-network

pkg/cluster/cluster.go, pkg/docker/pull.go
I was trying out footloose but totally forgot about starting `Docker` 😄. So I added a couple of lines to check first if the Docker daemon is running.
By running footloose it does give you an indication that this might be the case:
=> Check if Docker is running

pkg/cluster/cluster.go
This PR uses a new machine index to improve machine creation logic so that machines created from the different specs, but have the same index could avoid port collision.
Fixes #232 
/cc @cdavisafc
=> using a proper machine index to avoid port collision

pkg/api/api.go, pkg/api/response.go, pkg/client/client_test.go, serve.go
While playing around, I added a few things.
- added logger
- to show it started, etc. (with the options provided)
- in debug: it shows route matched
- added --debug flag (which enables a little more output)
- added really simple "API docs"
- all based on routes and methods for now
=> Update: footloose serve

pkg/cluster/cluster.go
If the machine has an anonymous volume then we must give the `-v` flag when we delete the container, otherwise the volume is leaked.
=> Remove docker volumes when machine is deleted

pkg/cluster/machine.go
Fetch the port configuration from Ignite itself now that it uses `containerd` as the default backend. This is kind of a "quick fix" refined version of https://github.com/weaveworks/footloose/pull/229 from quite some time ago, ultimately we do want to separate the Ignite and Docker backends completely to keep the code readable/maintainable (https://github.com/weaveworks/footloose/issues/220).
Fixes https://github.com/weaveworks/footloose/issues/228.
=> Fix `footloose ssh` for Ignite VMs

.goreleaser.yml
This PR is to fix error in .goreleaser.yaml due to deprecated field.
Signed-off-by: Tam Mach <sayboras@yahoo.com>
/cc @chanwit 
Testing was done locally as per below. Related docs https://goreleaser.com/deprecations#brewsgithub
<details>
<summary>Before</summary>
```
$ goreleaser check -f .goreleaser.yml
• loading config file       file=.goreleaser.yml
• checking config: 
• snapshotting     
• github/gitlab/gitea releases
• project name     
• building binaries
• creating source archive
• archives         
• linux packages   
• snapcraft packages
• calculating checksums
• signing artifacts
• docker images    
• artifactory      
• blobs            
• homebrew tap formula
• optimistically guessing `brew[0].installs`, double check
• DEPRECATED: `brews.github` should not be used anymore, …
```
=> fix(build): Fix goreleaser deprecated field in config
